name: Deploy
on:
  push:
    branches:
      - main
jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v3
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: "8.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Test with the dotnet CLI
        run: |
          dotnet user-secrets init --project src/Webapp/Webapp.csproj
          dotnet user-secrets set githubClientId ${{ secrets.OAUTH_GITHUB_CLIENT_ID }} --project src/Webapp/Webapp.csproj
          dotnet user-secrets set githubClientSecret ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }} --project src/Webapp/Webapp.csproj
          dotnet test
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only ./src/Webapp
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
